### ISSUE TITLE
gdrp in gdpr umbennen

### ISSUE THREAD

**Issue by qbi** [HopHubProject/HopHub#4]
Hallo,

einige Verzeichnisse oder Dateien haben die Buchstabenfolge `gdrp` im Namen. Aus dem Kontext heraus vermute ich, dass das `gdpr` heißen soll. Ich würde mich freuen, wenn ihr das umbennen würdet. :wink:

**Comment by zonque** [comment]
Danke für den Hinweis! Fixe ich gleich.
