### ISSUE TITLE
Adding event fails on mobile FF

### ISSUE THREAD

**Issue by Marwe** [HopHubProject/HopHub#5]
Adding an event fails on mobile Firefox.
Firefox even seems to crash on submitting and creates a report. Error is something like: "Firefox cannot load this page".

Maybe related to altcha, that thing kept spinning until the page failed. 
Tab was not able to reload the page, starting over in a fresh tab was necessary.

BTW, 30 chars for event name was too short in my case.

**Comment by zonque** [comment]
> Adding an event fails on mobile Firefox. Firefox even seems to crash on submitting and creates a report. Error is something like: "Firefox cannot load this page".
> 
> Maybe related to altcha, that thing kept spinning until the page failed. Tab was not able to reload the page, starting over in a fresh tab was necessary.

Very odd. I tried this with Firefox 125 On Android 13 and it worked flawlessly. Is this reproducible? Also, could you share the crash report?

**Comment by zonque** [comment]
> BTW, 30 chars for event name was too short in my case.

That was now increased to 50 in 10c622b. Does that cut your needs?

**Comment by Marwe** [comment]
Retried again and now it worked flawlessy to
* create event
* create a search for journey
* find my search
* contact me via Mail
* directly anwer to email address (with a ptoper email client, not outlook)

So, this issue can be closed - was only a temporary fail, cannot be teproduced.

Some further comments:
* reply-to might not work with microsoft customers/software
* mail delivery/contact took a while, maybe due to greylisting/spam score (see below)

```
Received: from director-03.heinlein-hosting.de [...] Sun, 14 Apr 2024 00:23:15 +0200
X-Spam-Flag: YES
X-Spam-Score: 6.299
X-Spam-Level: ******
X-Spam-Status: Yes, score=6.299 tagged_above=2 required=6	tests=[DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1,	DKIM_VALID_EF=-0.1, HS_RSPAMD_14=4, SPF_HELO_PASS=-0.001,	SPF_PASS=-0.001, URIBL_BLOCKED=0.001, URIBL_DBL_SPAM=2.5]	autolearn=no autolearn_force=no
Authentication-Results: spamfilter05.heinlein-hosting.de (amavisd-new);	dkim=pass (2048-bit key) header.d=hophub.xyz
Received: from hophub.xyz (hophub.xyz [37.218.243.92])	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)	 key-exchange X25519 server-signature RSA-PSS (4096 bits))	(No client certificate requested)	by mx2.mailbox.org (Postfix) with ESMTPS id 6CB7EA0B21	for <snip>; Sun, 14 Apr 2024 00:23:11 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=hophub.xyz; s=mail;	t=1713046471; [...]
Received: from hophub.xyz (10-42-0-20.web.hophub.svc.cluster.local [10.42.0.20])	by hophub.xyz (Postfix) with ESMTPS id 933381A7B124	for <snip>; Sat, 13 Apr 2024 22:14:31 +0000 (UTC)

```

**Comment by Marwe** [comment]
Forgot to mention crash report: the only option seemed to "print", which did not yield anything. Mozilla might have something ;)
Could not even copy the error message and had to close the tab before reloading worked...

**Comment by zonque** [comment]
> reply-to might not work with microsoft customers/software

Any context for that?

> mail delivery/contact took a while, maybe due to greylisting/spam score (see below)

Hmm, not sure what to do about this. Other inspection tools seem to be fairly happy with the mail we're sending:

https://www.mail-tester.com/test-8h3354emi

Any idea on how to improve them so that your spam detector likes them better?

**Comment by zonque** [comment]
> So, this issue can be closed - was only a temporary fail, cannot be teproduced.

Will do now. Please open another issue if you want to collaborate on improving the spam score :)
